let
    startDate = #date(2023, 1, 1),
    endDate = #date(2023, 12, 31),
    dates = List.Dates(startDate, Number.From(endDate - startDate) + 1, #duration(1,0,0,0)),
    table = Table.FromList(dates, Splitter.SplitByNothing(), {"Date"}),
    addedCustomColumns = Table.AddColumn(table, "Day of Week Name", each Date.DayOfWeekName([Date]), type text),
    addedCustomColumns = Table.AddColumn(addedCustomColumns, "Week Number", each Date.WeekOfYear([Date]), type number),
    addedCustomColumns = Table.AddColumn(addedCustomColumns, "Month Name", each Date.MonthName([Date]), type text),
    addedCustomColumns = Table.AddColumn(addedCustomColumns, "Month Number", each Date.Month([Date]), type number),
    addedCustomColumns = Table.AddColumn(addedCustomColumns, "Year", each Date.Year([Date]), type number)
in
    addedCustomColumns


// En este ejemplo, se establece la fecha de inicio en startDate y la fecha final en endDate. Luego, se crea una lista de fechas con la función List.Dates, que toma la fecha de inicio, la cantidad de días y la duración como argumentos. A continuación, se crea una tabla a partir de esta lista de fechas y se agregaron las columnas adicionales usando la función Table.AddColumn.
